tokenizer_name: "bert-base-uncased"
model_path: "../Models/bert-base-uncased/models--bert-base-uncased/snapshots/86b5e0934494bd15c9632b12f734a8a67f723594"
batch_size: 16
max_length: 300
checkpoint_dir: "../checkpoints"
checkpoint_interval: 2
data_path: "../Datasets/dataset_10k_val.csv"
path_technical_terms: "../Datasets/technical_terms_tokenized_BERT.csv"
